pub const SAMPLES_PER_SECOND_80: usize = 80;
pub const SAMPLES_PER_SECOND_800: usize = 800;
pub const SAMPLES_PER_SECOND_8000: usize = 8000;
pub const BYTES_PER_SAMPLE: usize = 4;
pub const META_SAMPLE_80_LEN: usize = 51;
pub const META_SAMPLE_800_LEN: usize = 41;
pub const META_SAMPLE_8000_LEN: usize = 33;

pub const SECONDS_PER_MINUTE: usize = 60;
pub const MINUTES_PER_HOUR: usize = 60;
pub const HOURS_PER_DAY: usize = 24;
pub const DAYS_PER_WEEK: usize = 7;
pub const DAYS_PER_MONTH: usize = 30;
pub const MONTHS_PER_YEAR: usize = 12;

pub const SECONDS_PER_FIFTEEN_MINUTES: usize = SECONDS_PER_MINUTE * 15;
pub const SECONDS_PER_HOUR: usize = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
pub const SECONDS_PER_DAY: usize = SECONDS_PER_HOUR * HOURS_PER_DAY;
pub const SECONDS_PER_WEEK: usize = SECONDS_PER_DAY * DAYS_PER_WEEK;
pub const SECONDS_PER_TWO_WEEKS: usize = SECONDS_PER_WEEK * 2;
pub const SECONDS_PER_MONTH: usize = SECONDS_PER_DAY * DAYS_PER_MONTH;
pub const SECONDS_PER_YEAR: usize = SECONDS_PER_MONTH * MONTHS_PER_YEAR;

pub const DEFAULT_MEASUREMENT_TTL: usize = SECONDS_PER_DAY;
pub const DEFAULT_TRENDS_TTL: usize = SECONDS_PER_TWO_WEEKS;
pub const DEFAULT_EVENTS_TTL: usize = SECONDS_PER_MONTH;
pub const DEFAULT_INCIDENTS_TTL: usize = SECONDS_PER_YEAR;
pub const DEFAULT_PHENOMENA_TTL: usize = SECONDS_PER_YEAR * 2;

pub const ESTIMATED_EVENTS_PER_SECOND: f64 = 0.00003116867161164198;
pub const ESTIMATED_INCIDENTS_PER_SECOND: f64 = 0.000000803914475264434;
pub const ESTIMATED_PERCENT_EVENT_DATA_DURATION: f64 = 0.06263335103845011;
pub const ESTIMATED_PERCENT_INCIDENT_DATA_DURATION: f64 = 0.002724681841042579;
//pub const ESTIMATED_PERCENT_EVENT_TO_INCIDENT: f64 = 0.5578222761952533;
pub const ESTIMATED_EVENT_LEN_S: usize = 2010;
pub const ESTIMATED_INCIDENT_LEN_S: f64 = 3389.0;

pub const ESTIMATED_BYTES_PER_META_SAMPLE_80: usize =
    SAMPLES_PER_SECOND_80 * BYTES_PER_SAMPLE * META_SAMPLE_80_LEN;
pub const ESTIMATED_BYTES_PER_META_SAMPLE_800: usize =
    SAMPLES_PER_SECOND_800 * BYTES_PER_SAMPLE * META_SAMPLE_800_LEN;
pub const ESTIMATED_BYTES_PER_META_SAMPLE_8000: usize =
    SAMPLES_PER_SECOND_8000 * BYTES_PER_SAMPLE * META_SAMPLE_8000_LEN;
pub const ESTIMATED_BYTES_PER_MEASUREMENT: usize = 0;
pub const ESTIMATED_BYTES_PER_TREND: usize = 2471;

pub const ESTIMATED_BYTES_PER_EVENT_80: usize =
    SAMPLES_PER_SECOND_80 * ESTIMATED_EVENT_LEN_S * BYTES_PER_SAMPLE;
pub const ESTIMATED_BYTES_PER_EVENT_800: usize =
    SAMPLES_PER_SECOND_800 * ESTIMATED_EVENT_LEN_S * BYTES_PER_SAMPLE;
pub const ESTIMATED_BYTES_PER_EVENT_8000: usize =
    SAMPLES_PER_SECOND_8000 * ESTIMATED_EVENT_LEN_S * BYTES_PER_SAMPLE;
pub const ESTIMATED_BYTES_PER_INCIDENT_80: usize =
    SAMPLES_PER_SECOND_80 * ESTIMATED_INCIDENT_LEN_S as usize * BYTES_PER_SAMPLE;
pub const ESTIMATED_BYTES_PER_INCIDENT_800: usize =
    SAMPLES_PER_SECOND_800 * ESTIMATED_INCIDENT_LEN_S as usize * BYTES_PER_SAMPLE;
pub const ESTIMATED_BYTES_PER_INCIDENT_8000: usize =
    SAMPLES_PER_SECOND_8000 * ESTIMATED_INCIDENT_LEN_S as usize * BYTES_PER_SAMPLE;

pub const ESTIMATED_BYTES_PER_PHENOMENA: usize = 4305;

pub const DEFAULT_GC_INTERVAL: usize = 600;
