pub struct Config {
    pub ticks: usize,
    pub percent_event_duration: f64,
    pub percent_event_to_incident: f64,
    pub mean_event_len: usize,
    pub samples_ttl: usize,
    pub measurements_ttl: usize,
    pub trends_ttl: usize,
    pub events_ttl: usize,
    pub incidents_ttl: usize,
    pub phenomena_ttl: usize,
    pub num_sensors: usize,
    pub bytes_per_sample: usize,
    pub bytes_per_measurement: usize,
    pub bytes_per_trend: usize,
    pub bytes_per_event: usize,
    pub bytes_per_incident: usize,
    pub bytes_per_phenomena: usize,
    pub print_info_every_n_ticks: usize,
    pub write_info_every_n_ticks: usize,
    pub out_file: String,
}
