
pdflatex:
	pdflatex energies-864131

all:
	pdflatex energies-864131; bibtex energies-864131; pdflatex energies-864131; pdflatex energies-864131

clean:
	rm *.aux; rm *.bbl; rm *.blg; rm *.log; rm *.out
